### ISSUE TITLE
XML Anpassen

### ISSUE THREAD

**Issue by RoyLemue** [RoyLemue/CAE-PA#8]
Rezeptinterface:
  - Module haben keine Position ( Validierung gegen Topologie)
  - Parameter haben keinen Typ(int, float, string) und keine Range (optional)
    - necessary schwer umzusetzen, da in Opc als überschreibbare Variable abgebildet, sprich unabhängig vom Funktionsaufruf

RunBlock:
  - wofür ist die linkedOpcId
  - ServiceId in exampleRecipe2 teilweise leer

**Comment by RoyLemue** [comment]
- RunBlock type SeriellerBlock hinzufügen (type="SeriellerBlock)
OpcRecipe2.xml
- 1. Dienstaufruf hat keine ServiceID
- generell ist das Rezept fehlerhaft, siehe Topology -> Alle Dienste vom Reaktor sind konti + dose vom Mixer
- Dose kann nur gestartet werden, wenn dispense zurückgesetzt wurde.

**Comment by ZiDa20** [comment]
i) runblock = serieller block: können wir gern machen, kann man doch aber als gegeben annehmen ?!

**Comment by RoyLemue** [comment]
Ja dann müsste ich den aber anders, als den seriellen Block behandeln, da
ein RecipeBlock durch den Type beschrieben wird.

2017-07-17 14:48 GMT+02:00 DaZi20 <notifications@github.com>:

**Comment by KellerDaDD** [comment]
**Rezeptinterface:**
Module
- Verschaltung und Topologie war Aufgabe der anderen Gruppe und bei uns nicht Pflicht (auch nicht die Validierung davon).
- Ich denke, es schränkt die Anwendung eher überflüssigerweise ein (Wenn man z. B. in Modul 2 etwas in einen Tank von Hand einleitet, kann dort trotzdem keine Funktion mehr ausgeführt werden, weil ja vorher Modul 1 mit einer Auspumpfunktion aufgerufen werden muss. --> Widerspruch)
- Wenn du es trotzdem einbauen willst, dann nimm am besten die interne Comos-Namensreihenfolge. Die kann man ja auch in Comos noch ändern.

Parameter
- Hatten wir eigentlich bewusst ohne Typ geplant, weil man es in Comos nicht validieren kann.
- Habe ich jetzt aber trotzdem in Comos eingebaut, es gibt ein Feld "Parametertyp", dass per vordefinierter Liste die Werte ["int","float","string","boolean"] annehmen kann.
- Außerdem habe ich "necessary" als Eigenschaft entfernt. Das war ja eh so eine sehr spezielle Erfindung für die Moka-Anlage, die wir übernommen hatten.


**Weiterhin:**
- linkedOpcId ist schon länger in den Stammobjekten nicht mehr drin und wird nicht verwendet, oder David?
- Die Dienste sind jetzt alle in Comos erfasst und sollten im RezeptInterface richtig ausgegeben werden. Bisher wurde ich nicht, welche Dienste kontinuierlich und welche es nicht sind.
- "Dienstaufruf" ist aus dem Rezept entfernt, und "Dose" habe ich durch "Mixer_Fill" ersetzt. Ich hoffe, dass Beispielrezept funktioniert dann so.

@RoyLemue 
Falls das Beispielrezept so nicht funktioniert, dann gib mir bitte ein neues funktionierendes vor, so dass ich es in Comos anpassen kann.

@DaZi20 
Wäre cool, wenn du in Comos den XML-Export dazu noch anpasst. Müsstest eigentlich nur in der Schnittstelle den Parametertypen hinzufügen und evtl. noch "linkedOpcId" löschen.
